version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: finSync_Db
    environment:
      POSTGRES_DB: finSync_Db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: finSync_pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: thalles@dev.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    networks:
      - postgres-network

volumes:
  postgres_data:

networks:
  postgres-network:
