-- Criação da tabela Wallet
CREATE TABLE tb_wallets (
    id UUID PRIMARY KEY,
    current_balance DOUBLE PRECISION,
    user_id UUID UNIQUE,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES tb_users(id) ON DELETE CASCADE
);

-- Criação da tabela BillsCategory
CREATE TABLE tb_billscategories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255)
);

-- Criação da tabela Bills
CREATE TABLE tb_bills (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    value DOUBLE PRECISION,
    due_date TIMESTAMP,
    paid BOOLEAN,
    category_id BIGINT,
    wallet_id UUID,
    CONSTRAINT fk_bills_category FOREIGN KEY (category_id) REFERENCES tb_billscategories(id) ON DELETE SET NULL,
    CONSTRAINT fk_bills_wallet FOREIGN KEY (wallet_id) REFERENCES tb_wallets(id) ON DELETE CASCADE
);

-- Criação da tabela Transaction
CREATE TABLE tb_transactions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type_transaction VARCHAR(255),
    value DOUBLE PRECISION,
    date TIMESTAMP,
    title VARCHAR(255),
    wallet_id UUID,
    CONSTRAINT fk_transactions_wallet FOREIGN KEY (wallet_id) REFERENCES tb_wallets(id) ON DELETE CASCADE
);
